In [15]:
import numpy as np

np.random.seed(42)
seq_len = 3
d_k = 4

Q = np.random.randn(seq_len, d_k)
K = np.random.randn(seq_len, d_k)
V = np.random.randn(seq_len, d_k)


In [16]:
def compute_scores(Q, K, V, d_k):
    scores = (Q @ K.T)/(np.sqrt(d_k))
    
    return scores

def softmax(X):
    return np.exp(X)/np.sum(np.exp(X), axis=1, keepdims=True)

In [17]:
def self_attention(Q, K, V, d_m):
    scores = compute_scores(Q, K, V, d_m)
    print(f"Scores shape: {scores.shape}")

    weights = softmax(scores)
    print(f"Weights shape: {weights.shape}")
    print(weights.sum(axis=1))
    
    output = weights @ V
    print(f"Output shape: {output.shape}")

    return output

In [18]:
output = self_attention(Q, K, V, d_k)
print(output)

Scores shape: (3, 3)
Weights shape: (3, 3)
[1. 1. 1.]
Output shape: (3, 4)
[[-0.32080902 -0.46976975 -0.19231589 -0.07677361]
 [-0.30249005 -0.57076556 -0.03681329  0.01880544]
 [-0.46126105 -0.36620523 -0.41823183  0.8562291 ]]


In [19]:
import torch

Q_tensor = torch.Tensor(Q)
K_tensor = torch.Tensor(K)
V_tensor = torch.Tensor(V)

torch_output = torch.nn.functional.scaled_dot_product_attention(Q_tensor, K_tensor, V_tensor)
print(torch_output, torch_output.shape)



tensor([[-0.3208, -0.4698, -0.1923, -0.0768],
        [-0.3025, -0.5708, -0.0368,  0.0188],
        [-0.4613, -0.3662, -0.4182,  0.8562]]) torch.Size([3, 4])
